theme: jekyll-theme-midnight
title: Justin Ollier aka Monsieur J
descripttion: Géomaticien (donc pas dévelopeur web) voici ma tentative de créer un site-web rassemblant mon C.V., mes petits projets de développements personnel, ainsi que quelques tuto pour moi même et un répertoire de bons liens. 